# Default values for veex-platform.
replicaCount: 1

image:
  repository: ghcr.io/veex-platform/veex-platform
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: registry.veexplatform.com
      paths:
        - path: /
          pathType: ImplementationSpecific

istio:
  enabled: false
  gateway: "istio-gateway"

postgresql:
  enabled: true
  auth:
    database: veexplatform
    username: veex
    password: veex_password

persistence:
  enabled: true
  size: 10Gi

platform:
  env:
    ALLOWED_ORIGINS: "*"
