{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "veex-admin.fullname" . }}
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  gateways:
    - {{ .Values.istio.gateway | default "istio-gateway" }}
  http:
    - route:
        - destination:
            host: {{ include "veex-admin.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
